<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists
# you can free to change all these codes/structure
# here A and B are list of lists

def matrix_mul(A, B):
    """
    This function returns the product of two matrices
    """  
    #Lets say Matrix A is of size (m*n) and matrix B is of size (n*K). Hence resultant product matrix must be of size (m*k)
    R=[] #result matrix
    for i in range(len(A)): #iterating through rows of R with length m
      lst=[] #empty list for each row
      for j in range(len(B[0])):  #iterating through thr columns of R with length k.
        lst.append(0) #appending 0s to fill all elements of matrix m*k with 0
      R.append(lst) 
    
    for i in range(len(R)):
        for j in range(len(R[0])):
            for a in range(len(B)):
                R[i][j]+=A[i][a]*B[a][j]
    return R
                
#Create a matrix by number of rows, number of columns and elements input by the user.    
def entermatrix(R,C):
  """
  This function inputs numbers and returns a matrix of the numbers
  """
  Matrix=[]
  for i in range(R): 
    lst=[]
    for j in range(C):
      a=float(input("Enter numbers: "))
      lst.append(a)
    Matrix.append(lst)
  return Matrix
#Entering own matrix
print("Enter first matrix M")
R1=int(input("Enter number of rows: "))
C1= int(input("Enter number of columns: "))
M=(entermatrix(R1,C1))
print("M={}".format(M))
print("-----------------")  
print("Enter second matrix N")
R2=int(input("Enter number of rows: "))
if C1 != R2:
  print("matrix multiplication not possible as number of columns in M is not equal to number of rows in N")
else:
  C2= int(input("Enter number of columns: "))
  N=(entermatrix(R2,C2))
  print("N={}".format(N))
  print("-----------------")
  print("The product of matrices M and N is")
  print("M*N= {}". format(matrix_mul(M,N))) 



Enter first matrix M
Enter number of rows: 2
Enter number of columns: 2
Enter numbers: 1
Enter numbers: 2
Enter numbers: 3
Enter numbers: 4
M=[[1.0, 2.0], [3.0, 4.0]]
-----------------
Enter second matrix N
Enter number of rows: 2
Enter number of columns: 5
Enter numbers: 1
Enter numbers: 2
Enter numbers: 3
Enter numbers: 4
Enter numbers: 5
Enter numbers: 5
Enter numbers: 6
Enter numbers: 7
Enter numbers: 8
Enter numbers: 9
N=[[1.0, 2.0, 3.0, 4.0, 5.0], [5.0, 6.0, 7.0, 8.0, 9.0]]
-----------------
The product of matrices M and N is
M*N= [[11.0, 14.0, 17.0, 20.0, 23.0], [23.0, 30.0, 37.0, 44.0, 51.0]]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
import pdb
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure
def pick_a_number_from_list(A):
  """
  This function returns the number of times a given number was picked out of a given number of random experiments, proportional on the magnitude of the number
  """
  A.sort()
  #Compute Normalised Sum
  S=sum(A)
  lst=[]
  for i in A: #............................
    n_s= i/S
    lst.append(n_s)

  #Compute Cumulative Normalised Sum cns
  cns=0
  lst_cns=[]
  for j in lst:
    cns+=j
    lst_cns.append(cns) #The cumulative normalised sum ranges between 0 to 1

  #sample one value
  from random import uniform
  r= uniform(0.0,1.0)
  for i in range(0, len(lst_cns)):
    if r<= lst_cns[i]:
      return A[i]

A= []
length_lst= int(input("Enter the length of list: "))
for j in range(length_lst):
  Num= float(input('Enter a number: '))
  A.append(Num)
print(A)

l=[]
for i in range(1,100):
  number= pick_a_number_from_list(A)
  print(number)

  

    




    
  

Enter the length of list: 10
Enter a number: 0
Enter a number: 5
Enter a number: 27
Enter a number: 6
Enter a number: 13
Enter a number: 28
Enter a number: 100
Enter a number: 45
Enter a number: 10
Enter a number: 79
[0.0, 5.0, 27.0, 6.0, 13.0, 28.0, 100.0, 45.0, 10.0, 79.0]
79.0
45.0
100.0
79.0
10.0
45.0
79.0
100.0
79.0
100.0
100.0
100.0
5.0
5.0
100.0
28.0
79.0
100.0
79.0
100.0
79.0
79.0
79.0
27.0
27.0
45.0
28.0
100.0
79.0
100.0
6.0
100.0
100.0
5.0
100.0
13.0
100.0
100.0
45.0
13.0
100.0
79.0
79.0
79.0
100.0
45.0
27.0
79.0
28.0
79.0
100.0
100.0
45.0
100.0
100.0
79.0
27.0
100.0
100.0
79.0
45.0
100.0
45.0
100.0
27.0
79.0
6.0
79.0
100.0
45.0
79.0
100.0
13.0
100.0
100.0
79.0
100.0
27.0
100.0
45.0
28.0
79.0
28.0
13.0
79.0
79.0
45.0
100.0
100.0
100.0
100.0
79.0
28.0
5.0
27.0
79.0
27.0
45.0
79.0


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
  """
  This function removes all non-digit elements of a given string and later replaces all digits with #
  """
  replace=''
  remove_nondigits= re.sub(r'[^0-9]+', replace, String) 
  if remove_nondigits== '':
    print("The string does not contain any digits")
  else:
     print(remove_nondigits)
  replace='#'
  replace_numbers= re.sub(r'[0-9]', replace,remove_nondigits )
  print(replace_numbers)

S=input("Enter a string containing mix of letters/numbers/symbols: ")
replace_digits(S)

Enter a string containing mix of letters/numbers/symbols: #2a$#b%c%561#
2561
####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure

def display_dash_board(students, marks):
  """
  This function returns the top 5 students(with highest marks), bottom 5 students (with lowest marks), and students between 25 and 75 perentile
  """
  result_dict=dict(zip(students, marks)) #converts two list to a dictionary where items from the 1st list are keys and items from the 2nd list are values
  asc=sorted(result_dict.items(), key=lambda t:t[1]) #sorts the dictionary in ascending order by value
  top_5_students =asc[-5: ] #computes the top 5 students by marks of the list of students
  top_5_students.reverse() #as the list is in ascending order of marks, the top 5 students are the last 5 students of the list. Hence the list is reversed to bring the top 5 students to the start of the list.
  print("The top 5 students with highest marks are")
  for a in top_5_students : #as the list is a list of tuples, each 'a' in the list points to a tuple
    print(a[0]," ", a[1]) #prints the 1st and 2nd element of a tuple with space in between
  print("*******************")
  print("The bottom 5 students with least marks are") 
  least_5_students= asc[0:5] #as the list is in ascending order of marks, the bottom 5 students are the 1st 5 students of the list.
  for b in  least_5_students:
    print(b[0]," ", b[1])
  print("*******************")
  def percentile(x,lst):
    """
    This function returns the POSITION of xth percentile value of a certain list of data
    """
    import math #to use floor and ceiling functions
    rank= x/100
    position= rank*(len(lst)) 
    if isinstance(position, float)==True:
      if ((position+1)-position)<= (position-(position-1)): #rounding off to the nearest whole number
        a=math.ceil(position)
      else:
        a=math.floor(position)
      percentile_position= int(a)
    else:
      percentile_position= position
    return percentile_position
  order_of_marks=sorted(marks)
  a=percentile(25,asc) #position of the 25th percentile of the list
  print("25th percentile= ",order_of_marks[a-1])
  b=percentile(75,asc) #position of the 75th percentile of the list
  print("75th percentile= ",order_of_marks[b-1])
  print("*******************")
  students_within_25_and_75 =asc[a:b-1]
  print("The students who got marks between 25th and 75th percentile are")
  for i in students_within_25_and_75:
    print(i[0]," ", i[1])

    
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
display_dash_board(Students, Marks)

The top 5 students with highest marks are
student8   98
student10   80
student2   78
student5   48
student7   47
*******************
The bottom 5 students with least marks are
student3   12
student4   14
student9   22
student6   43
student1   45
*******************
25th percentile=  22
75th percentile=  78
*******************
The students who got marks between 25th and 75th percentile are
student6   43
student1   45
student7   47
student5   48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math
# here S is list of tuples and P is a tuple of len=2
def closest_points_to_p(S, P):
  """
  This function returns the top 5 closest points from list S to given point P, based on Cosine Distance
  """
  lst_distance=[]
  for i in range(len(S)):
    cosine_distance= math.acos((S[i][0]*P[0]+S[i][1]*P[1])/(math.sqrt((S[i][0]**2)+(S[i][1]**2))*math.sqrt((P[0]**2)+P[1]**2)))
    lst_distance.append(cosine_distance)
  
  point_dist=dict(zip(S,lst_distance)) #returns a dictionary where key: value = points in S:distance from P
  asc= sorted(point_dist.items(), key= lambda t:t[1])
  print("The top 5 closest points to P{} are". format(P))
  for j in range(0,5):
    print(asc[j][0]," ", asc[j][1])  
  return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print() #print the returned values

The top 5 closest points to P(3, -4) are
(6, -7)   0.06512516333438509
(1, -1)   0.14189705460416438
(6, 0)   0.9272952180016123
(-5, -8)   1.2021004241368467
(-1, -1)   1.4288992721907328



<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [ ]:
#General equation of a line= ax+by+c
#Logic- if the distance of all red points from the line are positive and the distance of all blue points from the line are negative (or vice versa), print YES, else print NO.

import re
import math
def i_am_the_one(red,blue,lines):
  """
  This function prints YES if all red points are present on one side of the line (in lines) and blue points are present on the other side of the line, else it prints NO
  """
  #First we need to parse the coefficients of the line equations
  lst=[]
  for i in range(len(lines)):
    for j in range(len(lines[i])):
      l= [float(j) for j in re.split('[xXyY]', lines[i])] #Reference= https://stackoverflow.com/questions/56948506/how-to-extract-coefficients-from-a-line-equation-in-python-without-using-numpy/61547364#61547364
    lst.append(l)

  for i in lst:
    distance_red=[]
    distance_blue=[]
    for j in red:
      distance_from_line_red= (i[0]*j[0]+ i[1]*j[1]+i[2])/math.sqrt((i[0]**2)+(i[1]**2)) #Formula= Perpendicular distance of a point from a line of the form ax+by+c- https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_line
      distance_red.append(distance_from_line_red)
    for k in blue:
      distance_from_line_blue= (i[0]*k[0]+ i[1]*k[1]+i[2])/math.sqrt((i[0]**2)+(i[1]**2))
      distance_blue.append(distance_from_line_blue)
    if all(a>0 for a in distance_red) and all(b<0 for b in  distance_blue):
      print("YES")
    elif all(a<0 for a in distance_red) and all(b>0 for b in  distance_blue):
      print("YES")
    else:
      print("NO")
  return ("**********************")

Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
print(i_am_the_one(Red,Blue,Lines))

YES
NO
NO
YES
**********************


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:

def curve_smoothing(string):
  """
  This Function returns a smoothed string according to the given format.
  """
  #convert all numbers in the string from str to float 
    lst=string.split(',')
    for i in range(len(lst)):
        if lst[i]!='_':
            lst[i]=float(lst[i])
    #Left Boundary case= ("_,_,_,number)
    for index_1 in range(len(lst)):
        if type(lst[index_1])!=str:
            for a in range(index_1 + 1):
                lst[a]=(lst[index_1])/(index_1 + 1)
            index_value=(lst[index_1])
            next_index=index_1
            break

    #Middle case= (number,_,_,_,number)
    for index_2 in range(next_index + 1,len(lst)):
        if type(lst[index_2])!=str:
            temp_value=(index_value+lst[index_2])/(index_2-next_index+1)
            for b in range(next_index,index_2+1):
                lst[b]=temp_value
            index_value=(lst[index_2])    
            next_index=index_2

    #Right Boundary case= (number,_,_,_,_")
    count=0
    for index_3 in range(next_index + 1,len(lst)):
        if type(lst[index_3])!=float:
            count=lst.count('_')
            break
    value=index_value/(count+1)
    for index_3 in range(next_index,len(lst)):
        lst[index_3]=value
    
    #convert list back to string
    string2 = ' '.join([str(i) for i in lst])
    return string2
    

S= "_,_,30,_,_,_,50,_,_"
print(curve_smoothing(S))

10.0 10.0 12.0 12.0 12.0 12.0 4.0 4.0 4.0


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
  """
  This function returns the probability of a given condition that may occur in a matrix of size n*2, where there can be only 5 unique values F1,F2,F3,F4,F5 
  in column 1 and only 3 unique values S1, S2, S3 in column 2.
  """
  count_s1, count_s2, count_s3= 0,0,0

  for i in A:
    if i[1]=='S1':
      count_s1+=1
    if i[1]=='S2':
      count_s2+=1
    if i[1]=='S3':
      count_s3+=1
  count_f1_s1, count_f1_s2, count_f1_s3= 0,0,0
  count_f2_s1, count_f2_s2, count_f2_s3= 0,0,0
  count_f3_s1, count_f3_s2, count_f3_s3= 0,0,0
  count_f4_s1, count_f4_s2, count_f4_s3= 0,0,0
  count_f5_s1, count_f5_s2, count_f5_s3= 0,0,0

  for i in A:

    # a) Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)

    if i[0]=='F1' and i[1]=='S1':
        count_f1_s1+=1

    if count_f1_s1==0 or count_s1==0:
        a1=0
    else:
      a1=count_f1_s1/count_s1

    if i[0]=='F1' and i[1]=='S2':
        count_f1_s2+=1

    if count_f1_s2==0 or count_s2==0:
        a2=0
    else:
      a2=count_f1_s2/count_s2
    
    if i[0]=='F1' and i[1]=='S3':
        count_f1_s3+=1

    if count_f1_s3==0 or count_s3==0:
        a3=0
    else:
      a3=count_f1_s3/count_s3

    # b) Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)

    if i[0]=='F2' and i[1]=='S1':
        count_f2_s1+=1

    if count_f2_s1==0 or count_s1==0:
        b1=0
    else:
      b1=count_f2_s1/count_s1
    
    if i[0]=='F2' and i[1]=='S2':
      count_f2_s2+=1

    if count_f2_s2==0 or count_s2==0:
        b2=0
    else:
      b2=count_f2_s2/count_s2
    
    if i[0]=='F2' and i[1]=='S3':
        count_f2_s3+=1

    if count_f2_s3==0 or count_s3==0:
        b3=0
    else:
      b3=count_f2_s3/count_s3
    
    # c) Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)

    if i[0]=='F3' and i[1]=='S1':
        count_f3_s1+=1

    if count_f3_s1==0 or count_s1==0:
        c1=0
    else:
      c1=count_f3_s1/count_s1
    
    if i[0]=='F3' and i[1]=='S2':
        count_f3_s2+=1

    if count_f3_s2==0 or count_s2==0:
        c2=0
    else:
      c2=count_f3_s2/count_s2
    
    if i[0]=='F3' and i[1]=='S3':
        count_f3_s3+=1

    if count_f3_s3==0 or count_s3==0:
        c3=0
    else:
      c3=count_f3_s3/count_s3

    
  # d) Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
    
    if i[0]=='F4' and i[1]=='S1':
        count_f4_s1+=1

    if count_f4_s1==0 or count_s1==0:
        d1=0
    else:
      d1=count_f4_s1/count_s1
    
    if i[0]=='F4' and i[1]=='S2':
        count_f4_s2+=1

    if count_f4_s2==0 or count_s2==0:
        d2=0
    else:
      d2=count_f4_s2/count_s2
    
    if i[0]=='F4' and i[1]=='S3':
        count_f4_s3+=1

    if count_f4_s3==0 or count_s3==0:
        d3=0
    else:
      d3=count_f4_s3/count_s3

  # e)  Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
    
    if i[0]=='F5' and i[1]=='S1':
        count_f5_s1+=1

    if count_f5_s1==0 or count_s1==0:
        e1=0
    else:
      e1=count_f5_s1/count_s1
    
    if i[0]=='F5' and i[1]=='S2':
        count_f5_s2+=1

    if count_f5_s2==0 or count_s2==0:
        e2=0
    else:
      e2=count_f5_s2/count_s2
    
    if i[0]=='F5' and i[1]=='S3':
        count_f5_s3+=1

    if count_f5_s3==0 or count_s3==0:
        e3=0
    else:
      e3=count_f5_s3/count_s3

  print("a) Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3) respectively are {}, {}, {}".format(a1,a2,a3))
  print("b) Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3) respectively are {}, {}, {}".format(b1,b2,b3))
  print("c) Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3) respectively are {}, {}, {}".format(c1,c2,c3))
  print("d) Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3) respectively are {}, {}, {}".format(d1,d2,d3))
  print("e) Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3) respectively are {}, {}, {}".format(e1,e2,e3))
  print("*********************************************")
  print("The probailities in the fraction format are")
  print("a) P(F=F1|S==S1)= {}/{}, P(F=F1|S==S2)= {}/{}, P(F=F1|S==S3)= {}/{} ".format(count_f1_s1, count_s1,count_f1_s2, count_s2,count_f1_s3, count_s3 ))
  print("b) P(F=F2|S==S1)= {}/{}, P(F=F2|S==S2)= {}/{}, P(F=F2|S==S3)= {}/{} ".format(count_f2_s1, count_s1,count_f2_s2, count_s2,count_f2_s3, count_s3 ))
  print("c) P(F=F3|S==S1)= {}/{}, P(F=F3|S==S2)= {}/{}, P(F=F3|S==S3)= {}/{} ".format(count_f3_s1, count_s1,count_f3_s2, count_s2,count_f3_s3, count_s3 ))
  print("d) P(F=F4|S==S1)= {}/{}, P(F=F4|S==S2)= {}/{}, P(F=F4|S==S3)= {}/{} ".format(count_f4_s1, count_s1,count_f4_s2, count_s2,count_f4_s3, count_s3 ))
  print("e) P(F=F5|S==S1)= {}/{}, P(F=F5|S==S2)= {}/{}, P(F=F5|S==S3)= {}/{} ".format(count_f5_s1, count_s1,count_f5_s2, count_s2,count_f5_s3, count_s3 ))
  


A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a) Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3) respectively are 0.25, 0.3333333333333333, 0
b) Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3) respectively are 0.25, 0.3333333333333333, 0.3333333333333333
c) Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3) respectively are 0, 0.3333333333333333, 0.3333333333333333
d) Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3) respectively are 0.25, 0, 0.3333333333333333
e) Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3) respectively are 0.25, 0, 0
*********************************************
The probailities in the fraction format are
a) P(F=F1|S==S1)= 1/4, P(F=F1|S==S2)= 1/3, P(F=F1|S==S3)= 0/3 
b) P(F=F2|S==S1)= 1/4, P(F=F2|S==S2)= 1/3, P(F=F2|S==S3)= 1/3 
c) P(F=F3|S==S1)= 0/4, P(F=F3|S==S2)= 1/3, P(F=F3|S==S3)= 1/3 
d) P(F=F4|S==S1)= 1/4, P(F=F4|S==S2)= 0/3, P(F=F4|S==S3)= 1/3 
e) P(F=F5|S==S1)= 1/4, P(F=F5|S==S2)= 0/3, P(F=F5|S==S3)= 0/3 


<h3> Q9: Given two sentences S1, S2</h3>
You will be given two sentences S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def common_words(s1,s2):
  """
  This function prints the common words between two strings, the words that belong to set 1 but not set 2 and vice-verse
  """
  a=s1.lower()
  b=s2.lower()
  S1=a.split()
  S2=b.split()  
  print("The number of common words between String 1 and String 2  are")
  count=0
  for i in S1:
    if i in S2:
      count+=1
  print(count)
  print("*********************")
  print("The words in String 1 but not in String 2 are")
  lst1=[]
  for i in S1:
    if i not in S2:
      lst1.append(i)
  print(lst1)
  print("*********************")
  print("The words in String 2 but not in String 1 are")
  lst2=[]
  for j in S2:
    if j not in S1:
      lst2.append(j)
  print(lst2)

S1= "the first COLUMN F will contain only 5 uniques values"
S2= "the second column S WILL contain only 3 uniques values"
commonwords(S1,S2)


The number of common words between String 1 and String 2  are
7
*********************
The words in String 1 but not in String 2 are
['first', 'f', '5']
*********************
The words in String 2 but not in String 1 are
['second', 's', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
import math
def compute_log_loss(A):
  """
  This function returns the log loss of a matrix of size n*2
  """
    sum=0
    for i in A:
      f= (i[0]*math.log10(i[1]))+((1-i[0])*math.log10(1-i[1]))
      sum+=f
    loss = (-1)*(1/len(A))*(sum)
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
